version: "3.6"
# Based on https://docs.gitea.io/en-us/install-with-docker/

services:
  server:
    image: gitea/gitea:1.6
    ports: [] # use a proxy instead!
    volumes:
      - ${DATA_DIR}:/data
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
     - USER_UID=1000
     - USER_GID=1000
     - DB_TYPE=mysql
     - DB_HOST=db:3306
     - DB_NAME=gitea
     - DB_USER=gitea
     - DB_PASSWD=${MYSQL_PASSWORD}
     - SSH_DOMAIN=${DOMAIN_SSH}
     - ROOT_URL=https://${DOMAIN_WEB}/
     - SECRET_KEY=${SECRET_KEY}
    labels:
      caddy_0.address: ${DOMAIN_WEB}
      caddy_0.targetport: "3000"
      caddy_1.address: ${DOMAIN_SSH}
      caddy_1.targetport: "22"

  db:
    image: mariadb:10
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${DB_DATA_DIR}:/var/lib/mysql

networks:
  default:
    external: true
    name: ${NETWORK_NAME}
