version: "3.7"
services:
  gogs:
    image: gogs/gogs:0.11.66
    ports: [] # use a proxy instead!
    volumes:
      - ${DATA_DIR}:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      caddy_0.address: ${DOMAIN_WEB}
      caddy_0.targetport: "3000"
      caddy_1.address: ${DOMAIN_SSH}
      caddy_1.targetport: "22"
